const CountryList = [
  {
    Id: "1",
    //   sIcon: cnIcon1,
    title: "United Kingdom",
    slug: "United Kingdom",
  },
  {
    Id: "2",
    //   sIcon: cnIcon2,
    title: "Dubai, UAE",
    slug: "Dubai, UAE",
  },
  {
    Id: "3",
    //   sIcon: cnIcon3,
    title: "Denmark",
    slug: "Denmark",
  },
  {
    Id: "4",
    //   sIcon: cnIcon4,
    title: "Australia",
    slug: "Australia",
  },
  {
    Id: "5",
    //   sIcon: cnIcon5,
    title: "France",
    slug: "France",
  },
  {
    Id: "6",
    //   sIcon: cnIcon6,
    title: "Germany",
    slug: "Germany",
  },
  {
    Id: "7",
    //   sIcon: cnIcon7,
    title: "Greece",
    slug: "Greece",
  },
  {
    Id: "8",
    //   sIcon: cnIcon8,
    title: "Hungary",
    slug: "Hungary",
  },
  {
    Id: "9",
    //   sIcon: cnIcon9,
    title: "Iceland",
    slug: "Iceland",
  },
  {
    Id: "10",
    //   sIcon: cnIcon10,
    title: "Ireland",
    slug: "Ireland",
  },
  {
    Id: "11",
    //   sIcon: cnIcon11,
    title: "Italy",
    slug: "Italy",
  },
  {
    Id: "12",
    //   sIcon: cnIcon12,
    title: "Luxembourg",
    slug: "Luxembourg",
  },
  {
    Id: "13",
    //   sIcon: cnIcon8,
    title: "Hungary",
    slug: "Hungary",
  },
  {
    Id: "14",
    //   sIcon: cnIcon9,
    title: "Iceland",
    slug: "Iceland",
  },
  {
    Id: "15",
    //   sIcon: cnIcon10,
    title: "Ireland",
    slug: "Ireland",
  },
  {
    Id: "16",
    //   sIcon: cnIcon11,
    title: "Italy",
    slug: "Italy",
  },
  {
    Id: "17",
    //   sIcon: cnIcon12,
    title: "Luxembourg",
    slug: "Luxembourg",
  },
  {
    Id: "18",
    //   sIcon: cnIcon4,
    title: "Australia",
    slug: "Australia",
  },
  {
    Id: "19",
    //   sIcon: bigIcon1,
    title: "Canada",
    slug: "Canada",
  },
  {
    Id: "20",
    //   sIcon: bigIcon2,
    title: "America",
    slug: "America",
  },
  {
    Id: "21",
    //   sIcon: bigIcon3,
    title: "Australia",
    slug: "Australia",
  },
  {
    Id: "22",
    //   sIcon: bigIcon4,
    title: "UK",
    slug: "UK",
  },
  {
    Id: "23",
    //   sIcon: bigIcon5,
    title: "Spain",
    slug: "Spain",
  },
  {
    Id: "24",
    //   sIcon: bigIcon6,
    title: "Germany",
    slug: "Germany",
  },
];

export default CountryList;
